name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build & Make on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (if configured)
        run: npm run lint
        continue-on-error: true

      - name: Typecheck
        run: npm run typecheck
        continue-on-error: true

      - name: Build (renderer / main)
        run: npm run build

      - name: Create distributables (Linux)
        if: runner.os == 'Linux'
        run: npm run make

      - name: Create distributables (Windows)
        if: runner.os == 'Windows'
        run: npm run make
        shell: pwsh

      - name: Create distributables (macOS)
        if: runner.os == 'macOS'
        run: npm run make

      - name: Upload make artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge-make-${{ matrix.os }}
          path: out/make/**