name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set package version
        run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build and publish
        run: npm run make && npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_FORGE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
